import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import SearchBar from '../components/SearchBar';
import { useState } from 'react';
import Images from '../components/Images';

export default function Home() {
  const url = `https://images-api.nasa.gov/search`;
  const [items, setItems] = useState([]);
  // Search function passed to search bar
  const onSearch = async (value) => {
    const res = await fetch(url + '?q=' + value);
    let data = res.json();
    data
      .then((r) => {
        setItems(r.collection.items);
      })
      .catch((err) => console.log(err));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <Header />
      </div>
      <div>
        <SearchBar search={onSearch} />
      </div>
      <main>
        <div className={styles.images}>
          <Images data={items} />
        </div>
      </main>
    </div>
  );
}

// <main className={styles.main}>
// <h1 className={styles.title}>
// Welcome to <a href="https://nextjs.org">Next.js!</a>
// </h1>

// <p className={styles.description}>
// Get started by editing{' '}
// <code className={styles.code}>pages/index.js</code>
// </p>

// </main>

// <footer className={styles.footer}>
// <a
// href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
// target="_blank"
// rel="noopener noreferrer"
// >
// Powered by{' '}
// <span className={styles.logo}>
// <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
// </span>
// </a>
// </footer>
// </div>
